### PR TITLE
trigger hands-on

### PR DESCRIPTION
**Pull request by roshanirathi**

### CODE REVIEW

**Comment by roshanirathi** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/roshanirathi/prow-trial/pull/5#" title="Author self-approved">roshanirathi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=roshanirathi%2Fprow-trial).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/roshanirathi/prow-trial/blob/master/OWNERS)~~ [roshanirathi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roshanirathi** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/roshanirathi/prow-trial/pull/5#" title="Author self-approved">roshanirathi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=roshanirathi%2Fprow-trial).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/roshanirathi/prow-trial/blob/master/OWNERS)~~ [roshanirathi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roshanirathi** [comment]
@roshanirathi: What kind of bagel can fly? A plain bagel.

<details>

In response to [this](https://github.com/roshanirathi/prow-trial/pull/5#issuecomment-595698805):

>/joke


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by rosh-spectro** [comment]
test-suite

**Pull request merged**
